sqs:
  local:
    params:
      region: sqs
      endpoint: http://sqs:9324
      apiVersion: "2012-11-05"
    queueName:
      - cvs-edh-test-results-q
  remote:
    params:
      apiVersion: "2012-11-05"
    queueName:
      - cvs-edh-test-results-${BRANCH}-queue

targets:
  test-results:
    queue: test-results
    dlQueue: cvs-edh-dispatcher-test-results-${BRANCH}-dlq
    swaggerSpecFile: API_Vehicle_Testresults_28.1.yaml
    schemaItem: completeTestResults
    endpoints:
      INSERT: test-results
      MODIFY: test-results/{testResultId}
      REMOVE: test-results/{testResultId}
  activities:
    queue: activities
    dlQueue: cvs-edh-dispatcher-activities-${BRANCH}-dlq
    endpoints:
      INSERT: activities
      MODIFY: activities/{id}
      REMOVE: activities/{id}
