sqs:
  local:
    params:
      region: sqs
      endpoint: http://sqs:9324
      apiVersion: "2012-11-05"
    queueName:
      - cvs-update-store-queue
  remote:
    params:
      apiVersion: "2012-11-05"
    queueName:
      - cvs-update-store-${BRANCH}-queue

targets:
  test-results:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Vehicle_Test_Results_CVS_EDH_v1.yaml
    schemaItem: completeTestResults
  activities:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Activities_CVS_EDH_v1.yaml
    schemaItem: activity
  technical-records:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Vehicle_Tech_Records_CVS_EDH_v1.yaml
    schemaItem: completeTechRecordDB
